### ISSUE TITLE
Pagination support in Mission Manifest of rovers

### ISSUE THREAD

**Issue by Shwetank-Bhardwaj** [chrisccerami/mars-photo-api#114]
I am making an android application which displays a list of "objects under the "photos" key which are grouped by sol"
Currently, there are close to 2800 objects in that section.
This much data is causing UI to render slowly.
It would be great to have pagination support so that I can request according to my need

**Comment by paorpires** [comment]
Try not to fetch the photos directly, but going to rover -> camera -> sol date -> photos

**Comment by Shwetank-Bhardwaj** [comment]
I am not fetching photos. I am fetching Mission Manifest and displaying like in the screenshot
In this list, there are 2800 objects which are causing to render problems.
This is the endpoint I am hitting: [https://api.nasa.gov/mars-photos/api/v1/manifests/curiosity?api_key=DEMO_KEY](URL)

![WhatsApp Image 2020-07-16 at 11 44 49 PM](https://user-images.githubusercontent.com/54881078/87756844-7f333f00-c7be-11ea-8e8c-ef3c12c8c00d.jpeg)

**Comment by chrisccerami** [comment]
Would it be possible for you to fetch the full manifest and then paginate the data in your application, and only render a certain number of elements at a time?

**Comment by Shwetank-Bhardwaj** [comment]
It is possible and I was also thinking about that. You can add this issue as a suggestion for Mission Manifest API.
It would be efficient for an API to handle pagination.
