### ISSUE TITLE
Not receiving response from NASA APIs

### ISSUE THREAD

**Issue by josh-wilson6289** [chrisccerami/mars-photo-api#115]
Hey Chris,

I'm reaching out to let you know that there's currently an issue receiving data from this API.  I'm actually a student using it for a group project...it was working up until Friday but now we aren't getting responses from any of the NASA APIs.  Hopefully this is something being worked on, but wanted to bring it to your attention just in case.

Thanks so much for maintaining this, we've loved using the APIs!

-Josh

**Comment by chrisccerami** [comment]
Hey, not sure what was happening, but everything seems to be working now.
