### ISSUE TITLE
Long image download times

### ISSUE THREAD

**Issue by Alex-E-Mello** [chrisccerami/mars-photo-api#116]
I am trying to use this API to download images and the download times are being inconsistent. 

The 100x100 images can download instantly but the 1000x1000 images can take up to 30 seconds to download even though they are only 1MB files.

Here is a link for the Python code that I am using: https://pastebin.com/dZi8N9C2

**Comment by chrisccerami** [comment]
Unfortunately I can't help you with that. The images are not hosted from the API, they are hosted by NASA. The API simply links to the images.
