### ISSUE TITLE
Can't access latest photos

### ISSUE THREAD

**Issue by lamartm** [chrisccerami/mars-photo-api#118]
Hi using the API for a school project, when I try to access the latest photos I get an "API_KEY_MISSING" message. I tried my api key with different endpoints and it seems to be working there..

**Comment by chrisccerami** [comment]
Hi, without including your actual key, can you tell me how you're trying to access the API? What URL are you using?

**Comment by lamartm** [comment]
> Hi, without including your actual key, can you tell me how you're trying to access the API? What URL are you using?

I'm using the URL mentioned in the read me on Query for Latest Photo: https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/latest_photos

**Comment by chrisccerami** [comment]
You need to add your API key to that endpoint. How are you adding the API key?

**Comment by lamartm** [comment]
> You need to add your API key to that endpoint. How are you adding the API key?

https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/latest_photos&api_key=DEMO_KEY

**Comment by chrisccerami** [comment]
I see. You need to put a `?` at the beginning of parameters in a URL. A `&` is meant to separate multiple parameters. So your URL should look like https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/latest_photos?api_key=DEMO_KEY

**Comment by lamartm** [comment]
> I see. You need to put a `?` at the beginning of parameters in a URL. A `&` is meant to separate multiple parameters. So your URL should look like https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/latest_photos?api_key=DEMO_KEY

Oh god, mistake on my part! Thanks for your time!
