### ISSUE TITLE
Image size parameter for Preserverance

### ISSUE THREAD

**Issue by kriskda** [chrisccerami/mars-photo-api#128]
Just to consider. 

Current scrapper gets all available images without using parameter `extended=sample_type::full` / `extended=sample_type::thumbnail`. 
In https://mars.nasa.gov/rss/api/ feed JSON that is `"sample_type": "Full",` or `"sample_type": "Thumbnail",`. 

As result e.g. Sol-0 contains a lot of low res images (most from EDL cams) which are difficult to filter.

https://mars.nasa.gov/mars2020/multimedia/raw-images/ has "Image size" checkbox which uses `extended=sample_type:` parameter.

**Comment by chrisccerami** [comment]
Addressed by https://github.com/chrisccerami/mars-photo-api/pull/129
