### ISSUE TITLE
Filtering by camera parameters?

### ISSUE THREAD

**Issue by jumpjack** [chrisccerami/mars-photo-api#139]
it would be useful to be able to filter images by altitude/azimuth, both absolute w.r.t horizon/north and w.r.t rover tilt/heading.

**Comment by chrisccerami** [comment]
We don't have that sort of data available in the API's dataset.

**Comment by jumpjack** [comment]
The RSS API has a "mastAz" and "mastEl" parameter:

https://mars.nasa.gov/rss/api/?feed=raw_images&category=mars2020&feedtype=json

**Comment by jumpjack** [comment]
Found some hints on this page:
https://colab.research.google.com/drive/1SqTzhMo5NeVNZ6YTwsSpsssLH3vp5vX_?usp=sharing#scrollTo=03jJlvU4Hovx

Filtering by mastcam:
https://mars.nasa.gov/rss/api/?feed=raw_images&category=mars2020&feedtype=json&page=0&num=50&order=sol+asc&search=MCZ_LEFT&condition_2=0:sol:in&extended=sample_type::thumbnail,sample_type::full,product_type::raw

Which syntax is used here?
`extended=sample_type::thumbnail,sample_type::full,product_type::raw`

In "extended" group there are mastAz and mastEl; I found how to get exact matching, but what about intervals?
https://mars.nasa.gov/rss/api/?feed=raw_images&category=mars2020&feedtype=json&search=MCZ_LEFT&extended=mastAz::"266.764"

```
https://mars.nasa.gov/rss/api/?
feed=raw_images&
category=mars2020&
feedtype=json&
search=MCZ_LEFT&
extended=mastAz::"266.764"
```
