### ISSUE TITLE
Permit :rover_id in photos controller

### ISSUE THREAD

**Issue by mxkay** [chrisccerami/mars-photo-api#140]
I notice when I run a development version of the API, the console outputs `Unpermitted parameter: :rover_id` when I make a simple request like GET `localhost:3000/api/v1/rovers/curiosity/photos?sol=10` via Insomnia. The request successfully serves the data with a status 200, but the red text in my console is concerning. It goes away when I permit `:rover_id` in photos_controller.rb

Are others experiencing this as well, or is this isolated to me?

**Comment by chrisccerami** [comment]
Thanks, this was resolved by your PR.
