### ISSUE TITLE
Update frequency?

### ISSUE THREAD

**Issue by schultzisaiah** [chrisccerami/mars-photo-api#142]
I am 100% a ruby noob, and while I did make an attempt to glean any hints from the source code about possible schedule for the scraper(s), I was not at all successful.

I'm am using this api to (hopefully) make a first-rate Android app, but I think I need to better understand the scraping frequency to decide how it might fit my needs.

Currently, I'm asking from the perspective of Perseverance, but I have plans to expand to the other rovers as well.

Thanks for your time!

**Comment by chrisccerami** [comment]
Hi, the scraping process runs daily at midnight UTC.
