### ISSUE TITLE
Read Hazard Avoidance Camera

### ISSUE THREAD

**Issue by sunwangshu** [chrisccerami/mars-photo-api#15]
It should be "Rear" instead.
https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?sol=1000&api_key=DEMO_KEY

**Comment by chrisccerami** [comment]
Wow, thanks for the heads up. I'll get this fixed asap.

**Comment by chrisccerami** [comment]
Should be cleared up now. Thanks again @sunwangshu! :rainbow:
