### ISSUE TITLE
Api not returning photos recently

### ISSUE THREAD

**Issue by gus-t27** [chrisccerami/mars-photo-api#161]
Making a query to the api by earth date for example: 

[https://api.nasa.gov/mars-photos/api/v1/rovers/perseverance/photos?api_key=DEMO_KEY&earth_date=2021-10-08](https://api.nasa.gov/mars-photos/api/v1/rovers/perseverance/photos?api_key=DEMO_KEY&earth_date=2021-10-08)

Not returning any photos for perseverance or curiosity as of late. Some days in the last couple of weeks it has returned a couple of photos and most of them have looked rather odd! Usually this api returns 40 photos on average a day from each rover.

Anyone know what could be the issue here?

Thanks in advance for any info!

**Comment by chrisccerami** [comment]
From NASA: `We are in Mars solar conjunction, the period when the Sun comes between Mars and Earth, blocking our signals. This means Perseverance will temporarily pause sending us back raw images for about two weeks. Check back for new images after Oct. 18.`. The latest photo that exists from Perserverance was from October 18.
