### ISSUE TITLE
sol vs max_sol

### ISSUE THREAD

**Issue by Orbyt** [chrisccerami/mars-photo-api#22]
What is the difference between the `sol` value and the rover objects `max_sol`  value? Im assuming that `max_sol` is the number of sols that rover has been on the planet, but then what is the `sol` value?

**Comment by chrisccerami** [comment]
The `sol` value represents the sol of the rover's expedition on which a photo was taken. You're right about `max_sol`. `sol` is an attribute of a photo whereas `max_sol` is an attribute of a rover.
