### ISSUE TITLE
Thanks for creating this API as the JPL curiosity feed is broken

### ISSUE THREAD

**Issue by open768** [chrisccerami/mars-photo-api#23]
Thanks so much for creating this API 

I've been using the undocumented API http://mars.jpl.nasa.gov/msl-raw-images/image/image_manifest.json, but the catalog_urls for historic sols for that API have been returning access denied recently. I'm hoping that this API is more stable :-)

I use these apis for my mars browser http://mars-browser.co.uk/curiosity/, a simple open crowd sourced image classification platform for space data.

which I was planning to extend for spirit and discovery too.. I see this feed has that data so very excited to see what I can do with it :-)

**Comment by chrisccerami** [comment]
I'm glad it's going to be useful to people. I didn't even realize there was an undocumented API, which is why I built this one.
