### ISSUE TITLE
Sol 0 MARDI

### ISSUE THREAD

**Issue by alexandrebodin** [chrisccerami/mars-photo-api#24]
Hello,

Thanks for this API. I'm trying to access sol 0 with cam MARDI for the curiosity rover, I do get data but the images' links are broken. 

Thanks

**Comment by chrisccerami** [comment]
Unfortunately, there's nothing I can do about this. It seems as though these images must have been moved or deleted at some point by NASA. If you look here, http://mars.nasa.gov/msl/multimedia/raw/?s=0&camera=MARDI, you can see that all of the images are broken in NASA's gallery as well. I can attempt to contact someone within their Open Information Center, but I can't guarantee any results.

**Comment by open768** [comment]
I get the same problem using the undocumented json api :-( have reported it as a bug on nasa api github and to the webmasters as a permissions problem. it seems to stem from a permissions problem on the pds used by the jpl team which is restricting access to all but the latest sols :-(. hopefully someone will resolve it in the  new year when they're back from vacations

Sent from Yahoo Mail on Android 
 
  On Mon, Dec 28, 2015 at 14:18, Chris C Cerami<notifications@github.com> wrote:   
Unfortunately, there's nothing I can do about this. It seems as though these images must have been moved or deleted at some point by NASA. If you look here, http://mars.nasa.gov/msl/multimedia/raw/?s=0&camera=MARDI, you can see that all of the images are broken in NASA's gallery as well. I can attempt to contact someone within their Open Information Center, but I can't guarantee any results.

**Comment by alexandrebodin** [comment]
That's what I figured, didn't know if you had any way of fixing it :) 

Thanks a lot.

**Comment by open768** [comment]
Not sure if its related but I contacted the PDS operator to see if they could help with the broken raw image json api http://mars.jpl.nasa.gov/msl-raw-images/image/image_manifest.json.
PDS dont actually operate this but have helpfully said they would ask around to see who might be able to help. Well let you know if this gets fixed as it might also fix the problem with this API.
 

    On Wednesday, 30 December 2015, 10:07, Alex .B <notifications@github.com> wrote:
 

 That's what I figured, didn't know if you had any way of fixing it :) Thanks a lot.—

**Comment by open768** [comment]
hi the nasa pds operator has fixed my issue with the json api. maybe yours is fixed too :-) as a result?

**Comment by alexandrebodin** [comment]
Yes It did ! Thanks a lot. I'm working on a fun project I can finally rely on the data now :D

**Comment by chrisccerami** [comment]
Glad to hear this has been resolved by NASA. I'm thinking this issue can be closed? @open768 @alexandrebodin

**Comment by open768** [comment]
Sounds like a Plan. Nb Chris rather than screen scraping why not consider using the json API for curiosity data.

Sent from Yahoo Mail on Android 
 
  On Tue, 5 Jan, 2016 at 23:18, Chris C Cerami<notifications@github.com> wrote:   
Glad to hear this has been resolved by NASA. I'm thinking this issue can be closed? @open768 @alexandrebodin
