### ISSUE TITLE
request: remove restriction of 25 rows for certain API calls

### ISSUE THREAD

**Issue by open768** [chrisccerami/mars-photo-api#26]
Hello the restriction to 25 rows returned could be a problem when querying a sol. For example if an application wanted to show the thumbnails for sol 42, which contains 2831 photos it would have to make 114 api calls within a very short period of time to get information about the photos available. 

This could 
* overload your servers if a number of applications did this at the same time.
* exhaust the number of calls allowed per API key quickly

instead it would be useful instead to return the manifest that gave summary details about all the photos available in the sol ie

{
  "sol": 42,
  images:[
    {"instrument": "FHAZ_RIGHT_B, "itemName": "FRB_504551158EDR_T0520004FHAZ00323M_"},
    {...},
    ...
  ]
}

**Comment by chrisccerami** [comment]
@open768 I'll look into this when I get a chance to work on it. I think I can probably remove the limit from the API without causing too much of a performance problem. The pagination is really a relic of when this app had views instead of being a raw API and should have been removed.

**Comment by open768** [comment]
Thanks. Dont worry too much about me, the json api I was using is back and seems to be supported by NASA so I'll continue using it.  
My application is http://www.mars-browser.co.uk/curiosity/ and exposes its own restful APIs that transform and cache data from the following data sources without needing a relational database.
These are the sources I use   
   - this is the article that inspired me
   - this is where the browser began: http://mars.jpl.nasa.gov/msl-raw-images/image/image_manifest.json
   - a cool map resource: http://curiosityrover.com/
   - MSL notebook: https://an.rsl.wustl.edu/msl/mslbrowser
   - raw images: http://mars.nasa.gov/msl/multimedia/
   - PDS: http://pds-imaging.jpl.nasa.gov/volumes/msl.html
   - Software Interface Spec: http://pds-imaging.jpl.nasa.gov/data/msl/MSLMST_0005/DOCUMENT/MSL_MMM_EDR_RDR_DPSIS.PDF
   - Curiosity Locations: http://mars.jpl.nasa.gov/msl-raw-images/locations.xml
   - Where is Curiosity: http://mars.jpl.nasa.gov/msl/mission/whereistherovernow/
   - Gigapans by Neville Thompson: http://www.gigapan.com/profiles/pencilnev
   - Mars taxonomy (USGS): http://planetarynames.wr.usgs.gov/GIS_Downloads


 

    On Wednesday, 6 January 2016, 4:42, Chris C Cerami <notifications@github.com> wrote:
 

 @open768 I'll look into this when I get a chance to work on it. I think I can probably remove the limit from the API without causing too much of a performance problem. The pagination is really a relic of when this app had views instead of being a raw API and should have been removed. —

**Comment by chrisccerami** [comment]
This pagination has been removed from the V1 API endpoint.
