### ISSUE TITLE
duplicate rover information in API call

### ISSUE THREAD

**Issue by open768** [chrisccerami/mars-photo-api#27]
I noticed that the api featured on the documentation https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?sol=1000 provides duplicate information about the rover for each photo row.

the following information is repeated

>"rover":{"id":5,"name":"Curiosity","landing_date":"2012-08-06","max_sol":1205,"max_date":"2015-12-27","total_photos":230000,"cameras":[{"name":"FHAZ","full_name":"Front Hazard Avoidance Camera"},{"name":"NAVCAM","full_name":"Navigation Camera"},{"name":"MAST","full_name":"Mast Camera"},{"name":"CHEMCAM","full_name":"Chemistry and Camera Complex"},{"name":"MAHLI","full_name":"Mars Hand Lens Imager"},{"name":"MARDI","full_name":"Mars Descent Imager"},{"name":"RHAZ","full_name":"Rear Hazard Avoidance Camera"}]}},

**Comment by chrisccerami** [comment]
That's correct, that's because each photo record includes information about the rover to which it belongs. That's a feature and not a bug. Thanks for raising the issue though.
