### ISSUE TITLE
Max sol and number of items in manifest

### ISSUE THREAD

**Issue by kriskda** [chrisccerami/mars-photo-api#38]
So I'm looking at Curiosity manifest right now:
https://api.nasa.gov/mars-photos/api/v1/manifests/Curiosity?api_key=DEMO_KEY
It says "max_sol":1504 but last item in "photos" array is from Sol-1474. There are no items above 1474.

On the other hand I can access 1504:
https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?sol=1504&api_key=DEMO_KEY

**Comment by chrisccerami** [comment]
@kriskda thanks for raising the issue. Seems like it's being caused by the manifest cache not being updated. I'll take a look at it during the upcoming long weekend.

**Comment by chrisccerami** [comment]
I'm pretty sure this is resolved now. Let me know if you have any further issues.
