### ISSUE TITLE
Bring back pagination

### ISSUE THREAD

**Issue by armadsen** [chrisccerami/mars-photo-api#46]
I note that pagination was removed (see #35). I understand the reason for removing it, but would like to request that it be brought back and made optional. My reasoning is that for sols with a large number of photos, requesting, receiving, and parsing the whole list of photo info takes a long time. I'm building a mobile app where that delay means staring at a blank page for a while, and where it would make a lot of sense to paginate the data anyway, since the UI displays a scrollable view with a relatively small number of photos on screen at one time.

Perhaps including the `page=` query parameter could turn on paging, but if its left out, the default is to return all photos?

**Comment by chrisccerami** [comment]
I'll look into this when I get a chance. Seems like a reasonable idea.

**Comment by krtkush** [comment]
I second this. Pagination can be really useful in certain cases.

**Comment by AndreaMiotto** [comment]
Yup please, bring back pagination. Or at least a "random query" that returns some random images between all the sol
