### ISSUE TITLE
Api not working - build failure

### ISSUE THREAD

**Issue by izactherobot80** [chrisccerami/mars-photo-api#47]
I have a class project using this api and it stopped working about a week ago.  I looks like the build is failing.

**Comment by chrisccerami** [comment]
Can you give me some more detail? What isn't working?

**Comment by izactherobot80** [comment]
Sure.  I can't seem to get data back for any dates on any cameras after Sol
1635 or March 12 2017 for Curiosity.  Every date before that works fine.

**Comment by simplon-romainB** [comment]
hello,

I have the same problem, no further photos after max_sol 1635 on Curiosity.(2017/03/12)

**Comment by chrisccerami** [comment]
It seems like this is a billing issue with Heroku. I'm not sure if their pricing changed, but the workers that were getting new images have been turned off. I'll have it resolved soon.

**Comment by chrisccerami** [comment]
Ah, actually I'm wrong. There is a technical issue. I'm looking into it.

**Comment by chrisccerami** [comment]
Ok I just deployed a fix. The newest images should be updated tonight, so you should see them in the API tomorrow.

**Comment by simplon-romainB** [comment]
thanks a lot it works !!

**Comment by izactherobot80** [comment]
Seems to be working. Thanks
