### ISSUE TITLE
API isnt getting new curiosity photos 

### ISSUE THREAD

**Issue by qwazwsx** [chrisccerami/mars-photo-api#69]
I've noticed that the API doesn't seem to be returning new images for the Curiosity rover. I tried to get images for yesterday, 2017-11-9 / sol 1870, I tried the following url's

[https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?earth-date=2017-11-9](https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?earth-date=2017-11-9)

[https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?earth-date=2017-11-09](https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?earth-date=2017-11-09)

[https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?sol=1870](https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/photos?sol=1870)

All of which returned no photos. But when I go to the [NASA rover raw image page](https://mars.nasa.gov/msl/multimedia/raw/?s=1870&camera=FHAZ_) I see images for that date. I'm not familiar with the language you are scraping with, so, unfortunately,  I can't help much. But my assumption would be that they changed the format of the website, breaking your scraper. But from basic inspection of your regex [here](https://github.com/chrisccerami/mars-photo-api/blob/c631f05b9b1d57658a0294cf1e22c80379217006/app/models/curiosity_scraper.rb), nothing *seems* to be broken.

thanks!

**Comment by chrisccerami** [comment]
Hey, thanks for the report. I finally got a chance to look into this and it seems like the scraper was crashing when attempting to open a URL. I'm not sure what changed between October 18th and now, but I believe I just pushed a fix, so I'll check back in a few hours and see if the new photos appear.

**Comment by qwazwsx** [comment]
:) Seems like that fixed it! Thanks!

**Comment by chrisccerami** [comment]
It looks like the records should be up to date again. Thanks again for bringing this to my attention.
