### ISSUE TITLE
[idea] Images from latest day

### ISSUE THREAD

**Issue by PawelPleskaczynski** [chrisccerami/mars-photo-api#70]
Would it be possible to add an attribute to this API, which would give JSON file with photos from the desired rover from the latest day/sol only? The link could be looking like this: `https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/photos?latest_sol=true&api_key=apikey`

**Comment by chrisccerami** [comment]
That's not a bad idea. I do like the thought of a static link that will always give the latest photos.

**Comment by PawelPleskaczynski** [comment]
I'm sorry to interrupt you, but I would like to know if this option will be added?

**Comment by frankiescott** [comment]
hey @PawelPleskaczynski 

in case you haven't figured it out yet, you can query the manifest `https://mars-photos.herokuapp.com/api/v1/manifests/curiosity` to obtain two data points `max_sol` and `max_date` that will provide you with the latest sol/date for which photos exist. then you can query the API as normal. 

of course, it would be convenient to omit the first step and just add a parameter to the query.. figured I'd share my workaround though.

**Comment by chrisccerami** [comment]
This has now been implemented at the `rovers/<name>/latest_photos` endpoint.
