### ISSUE TITLE
[idea] Earth Date in manifests

### ISSUE THREAD

**Issue by flooyd** [chrisccerami/mars-photo-api#74]
Hello :)

I am making a little site for browsing images from the rovers, and I was wondering if it would be possible to make a manifest query that lists them by the Earth date rather than Sol. My app lets users select an earth date, rover, and camera, and I would like to be able to limit the cameras available based on the day selected. I could try to convert the earth date to Sol, but that seems pretty complex...

**Comment by chrisccerami** [comment]
I don't think that would be too hard to add.

**Comment by chrisccerami** [comment]
Should be good to go!
