### ISSUE TITLE
Filter by Camera

### ISSUE THREAD

**Issue by freddyh** [chrisccerami/mars-photo-api#79]
The example in the README shows you can query by camera name and an earth date. Is it possible to query the rover photos by camera only?

**Comment by chrisccerami** [comment]
If you mean can you query by camera without supplying either an earth date or a sol, then no. The amount of data would be far too large, so some kind of date filter is required. If you want to know what dates have data for a particular camera you can request the manifest.

**Comment by freddyh** [comment]
but why not just page the results if the results are large?
