### ISSUE TITLE
Access issues on assorted http requests

### ISSUE THREAD

**Issue by aaronbrezel** [chrisccerami/mars-photo-api#82]
There seem to be some issues making http requests at both the /latest_photos and /manifests endpoints

The following three urls all return the same error message: 

API_KEY_MISSING
No api_key was supplied. Get one at https://api.nasa.gov:443 

https://api.nasa.gov/mars-photos/api/v1/manifests/curiosity&api_key=UNIQUE_KEY
https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/manifests/curiosity&api_key=UNIQUE_KEY
https://api.nasa.gov/mars-photos/api/v1/rovers/curiosity/latest_photos&api_key=UNIQUE_KEY

My key works for standard photo queries.

Thank you!

And thank you for creating this API

**Comment by Dabbyd123** [comment]
Your first url is close but you need to change the '&' to '?' character after you specify the rover.  It should look like this: 

https://api.nasa.gov/mars-photos/api/v1/manifests/curiosity?api_key=UNIQUE_KEY
