### ISSUE TITLE
Cameras in manifests

### ISSUE THREAD

**Issue by asos-filippob** [chrisccerami/mars-photo-api#83]
Hey, I think it would be more useful to get the set of cameras for each rover from the `/manifests` endpoint rather than from each `"rover"` entity in each of the `/latest_photos` item so that we can get a list of all available cameras to query beforehand.

Thanks for the work :D

**Comment by chrisccerami** [comment]
I think I understand what you're asking for, but given that the set of cameras for each Rover is static and listed in the documentation it just doesn't seem like it's of much actual practical value. Is there a use case I'm missing?

**Comment by asos-filippob** [comment]
Yeah my use case was originally to build a `feature set` for each rover, so given a rover I could know which cameras it is equipped with, instead of going to query `/latest_photos` and look into each of them. I theoretically would never be able to know if a given rover has a given camera as I would have to go through the set of photos and derive it from there.

It's definitely doable, but maybe could be simpler like that. Tbh I do not remember if the api can serve a list of pics for a specific camera, so that would have a practical use like: 'Given this rover X, which has the camera Y, give me all pictures taken with camera Y from latest photos'?

Thanks :D I kind of abandoned my pet project (a Flutter mobile app) a while ago, maybe I'll pick it up again soon :)

**Comment by asos-filippob** [comment]
I got your point anyway, there's not much to do, it's all static.

**Comment by chrisccerami** [comment]
Yeah, you can do that. The request would look like
https://mars-photos.herokuapp.com/api/v1/rovers/curiosity/latest_photos?camera=CHEMCAM

If you look at https://github.com/chrisccerami/mars-photo-api/blob/master/README.md#cameras you can see the list of cameras for each rover.

**Comment by asos-filippob** [comment]
Thank you!
