### ISSUE TITLE
API not updating past all 2463 

### ISSUE THREAD

**Issue by stirlingalgermissen** [chrisccerami/mars-photo-api#85]
Looks like the api has stopped updating, no new images are showing up past sol 2463 despite the raw image site updating.

**Comment by marc0tjevp** [comment]
I noticed the same. From `earth_date` 2019-07-11 there are no new images.

**Comment by chrisccerami** [comment]
Thanks for opening this issue. It looks the raw images site was completely rebuilt. I think I've found the updates that need making, I just want to make sure I have them thoroughly tested before pushing them to the live site. Hopefully within a couple of days everything will be back to normal.

**Comment by chrisccerami** [comment]
I believe everything should be back in order now. Let me know if anything else comes up.
