### ISSUE TITLE
Query without date

### ISSUE THREAD

**Issue by ArtemisFowlJnr** [chrisccerami/mars-photo-api#87]
This is a great API and all, but I'm trying to use it to get an image by rover and camera. I'm running into the problem that on many dates no images were taken by some camera. Would it be possible to query without a date, and receive a (paginated) list of every photo taken by that rover/camera? Thanks for your time - Artemis.

**Comment by chrisccerami** [comment]
There is no option to query without a date, and I don't really have any plans to add that option, just because of the amount of data. You can use the manifest endpoint however to see which dates have data for which cameras.
