### ISSUE TITLE
No updates since sol 2540

### ISSUE THREAD

**Issue by stirlingalgermissen** [chrisccerami/mars-photo-api#88]
Looks like the raw images website format changed

**Comment by cgibsonmm** [comment]
I am going to fork this and see if I can get the scrapper to start working again.

**Comment by cgibsonmm** [comment]
Here is a fix https://github.com/chrisccerami/mars-photo-api/pull/101

**Comment by chrisccerami** [comment]
I'm running the scraper on production now, so this should get things back to normal. Thanks for the help @cgibsonmm

**Comment by chrisccerami** [comment]
Everything should be up to date now.

**Comment by stirlingalgermissen** [comment]
Looks great, my bot started up as soon as this was deployed. Thank you
