### ISSUE TITLE
api.nasa.gov -> Mars Rover Photos -> Querying by Earth date -> earth_date has description as if it was sol

### ISSUE THREAD

**Issue by Vitouuu** [chrisccerami/mars-photo-api#90]
## Description
On https://api.nasa.gov/ page, on **Mars Rover Photos** section, **Querying by Earth date -> earth_date** parameter has an incorrect description.

## Screenshots
_____________
* earth_date (incongruent **description**, probably copied from **Querying by Martian Sol -> sol** ):
![image](https://user-images.githubusercontent.com/3942402/68170968-97c13900-ff50-11e9-8e8c-b32b654b5537.png)
_____________

## Note
Although it seems this doesn't belong to this particular repo, I couldn't find where to submit this bug for the general NASA API page, so I thought you being the maintainer could route this to the corresponding team. I hope it helps.

**Comment by chrisccerami** [comment]
I'll contact the folks I know over at NASA and see if they can get this corrected. Thanks for the heads up.
